# Recurring tasks for Solid Queue
generate_monthly_bills:
  class: GenerateMonthlyBillsJob
  schedule: "0 0 1 * *" # Run at midnight on the 1st of every month
fetch_economic_indicators:
  command: "CMF::IndicatorFetcher.call"
  schedule: "0 6 * * *" # Run every day at 6:00 AM
daily_charge_run:
  class: DailyChargeJob
  schedule: "0 8 * * *" # Run every day at 8:00 AM
